### ISSUE TITLE
Basic emojiID

### ISSUE THREAD

**Issue by Kasoar** [BeepIsla/discord-customstatus#2]
Hey BeepIsla, 
I got a question regarding emojiID's, I want to use the basic discord emojis in my status, for example a moving clock. But i can not figure out how to get the ID of the emoji. If the ID is not needed for the basic emojis than I can not figure out why the emoji I want to see does not show.
(I know how to get the ID of custom Emojis, this method does not work with the basic or standart Discord emojis)

**Comment by BeepIsla** [comment]
Default emojis do not have an emoji ID. Set emoji ID to `null` and emoji name to the unicode of the emoji you want. For example for a thinking emoji it would be: `🤔`

You can get the unicode's of all emojis by sending the emoji with a backslash (`\`) prefixed. For our example above you would send `\:thinking:` in a channel to get the unicode.

**Comment by Kasoar** [comment]
Thanks for the Info and the fast replay. I have already removed the ID of emojis but nothing happened, I guess discord is blocking that i some way. But still thanks for the help and for programming these things for us :D

**Comment by YarrakMC58** [comment]
It isnt blocked. Send the Code pls so i can help you. On my Discord it works

**Comment by Kasoar** [comment]
> It isnt blocked. Send the Code pls so i can help you. On my Discord it works

ok my dc is Kasoar#6430 @YarrakMC58

**Comment by YarrakMC58** [comment]
> > It isnt blocked. Send the Code pls so i can help you. On my Discord it works
> 
> ok my dc is Kasoar#6430 @YarrakMC58

I added you D A H A B#6969
