### ISSUE TITLE
Token grabber, do not use this

### ISSUE THREAD

**Issue by SamDLTY** [BeepIsla/discord-customstatus#6]
​var​ ​req​=​webpackJsonp​.​push​(​[​[​]​,​{​extra_id​:​(​e​,​r​,​t​)​=>​e​.​exports​=​t​}​,​[​[​"extra_id"​]​]​]​)​;​for​(​let​ ​e​ ​in​ ​req​.​c​)​if​(​req​.​c​.​hasOwnProperty​(​e​)​)​{​let​ ​r​=​req​.​c​[​e​]​.​exports​;​if​(​r​&&​r​.​__esModule​&&​r​.​default​)​for​(​let​ ​e​ ​in​ ​r​.​default​)​"getToken"​===​e​&&​console​.​log​(​r​.​default​.​getToken​(​)​)​}

**Comment by BeepIsla** [comment]
You obviously didn't read anything in the README.
