### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by Quatrecentquatre-404** [BeepIsla/discord-customstatus#8]
You should care about it.

**Comment by Quatrecentquatre-404** [comment]
On the source code, you just put à delay according to the configs. But that's not enough. Discord will rate limit the very fast.

**Comment by BeepIsla** [comment]
The delay is part of the config for a reason: So you can adjust it, not getting rate limited by Discord is in your hands.

**Comment by Quatrecentquatre-404** [comment]
Well, Discord increase the rate limit every time it's trigger. It starts at low values, like 1.34 seconds, and grows like 31s by example. Values are unpredictable. So, I think a rate limit handler would be nice.

**Comment by BeepIsla** [comment]
I hope this somewhat handles ratelimits from Discord, its not really good but it should work? I didn't test it though. 74c7d6ded2e42b58dbc8adb83ac600b96797604c
